version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - source $HOME/.cargo/env
      - uv sync

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt