"""Type stubs for the CEL Rust extension module."""

from typing import Any, Callable

class PreparedValue:
    """Opaque immutable CEL value created by :func:`prepare`."""

class Context:
    """Reusable native CEL context for prepared values and Python functions."""

    def __init__(self) -> None: ...
    def add_variable(self, name: str, value: PreparedValue) -> None: ...
    def add_function(self, name: str, function: Callable[..., Any]) -> None: ...

class Program:
    """Compiled CEL program."""

    def execute(self, context: Context) -> Any: ...

class OptionalValue:
    """Wrapper for CEL optional values."""

    @classmethod
    def of(cls, value: Any) -> OptionalValue: ...
    @classmethod
    def none(cls) -> OptionalValue: ...
    def has_value(self) -> bool: ...
    def value(self) -> Any: ...
    def or_value(self, default: Any) -> Any: ...
    def or_optional(self, other: OptionalValue) -> OptionalValue: ...

def prepare(value: Any) -> PreparedValue: ...
def compile(expression: str) -> Program: ...
def evaluate(expression: str, context: Context) -> Any: ...
